language: php

php:
  - 7.1

before_install:
  - sudo pip install codecov

before_script:
  - composer install --dev

script:
  - cd tests
  - phpunit --coverage-clover=coverage.xml

after_success:
  - codecov

notifications:
    slack: mhlsoftware:fJKaZkBD8t9wcxQtLV2rGo8x
