sudo: required

language: php

php:
  - 7.1

services:
  - docker

env:
  - DB_USER=symphonia
  - DB_NAME=symphonia
  - DB_PASS=1
  - APP_SECRET=f5b84ae43ca331692f484aee037ae24042e5702c

before_install:
#  - sudo apt-get update
#  - sudo pip install codecov
  - docker-compose up -d
  - docker ps -a


#before_script:
#  - composer install --dev

script:
  - phpunit --coverage-clover=coverage.xml

#after_success:
#  - codecov

notifications:
    slack: mhlsoftware:fJKaZkBD8t9wcxQtLV2rGo8x
