language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - sudo pip install codecov

before_script:
  - composer install --dev

script:
  - cd tests
  - phpunit --coverage-clover=coverage.xml

after_success:
  - codecov