version: "3"

services:
    web:
        image: miholeus/nginx:latest
        volumes:
            - .:/app:delegated
            - ./support/nginx/symphonia.dev:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        links:
            - php
    php:
        image: miholeus/php71:development
        tty: true
        depends_on:
            - database
        environment:
            - SYMFONY_ENV=${ENV}
            - SYMFONY__DATABASE__USER=${DB_USER}
            - SYMFONY__DATABASE__NAME=${DB_NAME}
            - SYMFONY__DATABASE__PASS=${DB_PASS}
            - SYMFONY__APP__SECRET=${APP_SECRET}
        volumes:
            - ./:/app
            - ./support/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        working_dir: /app
    database:
        build: 'support/database'
        volumes:
            - mysql_db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
volumes:
    mysql_db_data: