Symphonia\CoreBundle\Entity\ContentNode:
    type: entity
    table: content_nodes
    indexes:
        page_id:
            columns:
                - page_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        value:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        isinvokable:
            type: boolean
            nullable: false
            column: isInvokable
        params:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        pageId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: page_id
    lifecycleCallbacks: {  }
