Symphonia\CoreBundle\Entity\News:
    type: entity
    table: news
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        shortDescription:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: short_description
        detailDescription:
            type: text
            nullable: false
            length: 16777215
            options:
                fixed: false
            column: detail_description
        published:
            type: boolean
            nullable: false
            options:
                default: '0'
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        publishedAt:
            type: datetime
            nullable: true
            column: published_at
    lifecycleCallbacks: {  }
