Soulex\CoreBundle\Entity\ControllerAction:
    type: entity
    table: controller_actions
    indexes:
        controller_id:
            columns:
                - controller_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        action:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        params:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        controllerId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: controller_id
    lifecycleCallbacks: {  }
